version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    env_file: .env.test
    depends_on:
      - mysql_test

  mysql_test:
    image: mysql:8.0
    env_file: .env.test
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  mysql_test_data: