apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: integration-system
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_connections=200
    innodb_buffer_pool_size=512M