apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-system
  labels:
    app: integration-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: integration-system
  template:
    metadata:
      labels:
        app: integration-system
    spec:
      containers:
      - name: integration-system
        image: integration-system:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: integration-system-config
        - secretRef:
            name: integration-system-secrets
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi