apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-system
  namespace: integration-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: integration-system
  template:
    metadata:
      labels:
        app: integration-system
    spec:
      containers:
      - name: app
        image: integration-system:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5