apiVersion: v1
kind: Service
metadata:
  name: integration-system
  namespace: integration-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: integration-system